import { useState } from "react";
import { ToolPageLayout } from "@/components/Layout";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { useToast } from "@/hooks/use-toast";
import { Copy, Check } from "lucide-react";
import { SEO } from "@/components/SEO";
import { getToolSEO } from "@/data/toolsData";

export default function RobotsTxtGenerator() {
  const toolSEO = getToolSEO("/robots-txt-generator");
  const [allowAllBots, setAllowAllBots] = useState(true);
  const [enableCrawlDelay, setEnableCrawlDelay] = useState(false);
  const [crawlDelay, setCrawlDelay] = useState("10");
  const [sitemapUrl, setSitemapUrl] = useState("");
  const [disallowPaths, setDisallowPaths] = useState("");
  const [copied, setCopied] = useState(false);
  const { toast } = useToast();

  const generateRobotsTxt = () => {
    const lines: string[] = [];

    lines.push("# robots.txt generated by SEO Tools Hub");
    lines.push("");
    lines.push("User-agent: *");

    if (allowAllBots) {
      lines.push("Allow: /");
    } else {
      lines.push("Disallow: /");
    }

    if (disallowPaths.trim()) {
      const paths = disallowPaths.split("\n").filter((p) => p.trim());
      paths.forEach((path) => {
        const cleanPath = path.trim().startsWith("/") ? path.trim() : "/" + path.trim();
        lines.push(`Disallow: ${cleanPath}`);
      });
    }

    if (enableCrawlDelay && crawlDelay) {
      lines.push(`Crawl-delay: ${crawlDelay}`);
    }

    if (sitemapUrl.trim()) {
      lines.push("");
      lines.push(`Sitemap: ${sitemapUrl}`);
    }

    return lines.join("\n");
  };

  const output = generateRobotsTxt();

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(output);
      setCopied(true);
      toast({
        title: "Copied!",
        description: "robots.txt content copied to clipboard",
      });
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast({
        title: "Error",
        description: "Failed to copy to clipboard",
        variant: "destructive",
      });
    }
  };

  const downloadFile = () => {
    const blob = new Blob([output], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = "robots.txt";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <ToolPageLayout
      title="Robots.txt Generator"
      description="Generate a robots.txt file to control how search engine bots crawl and index your website."
      howToUse={
        <ol className="list-decimal list-inside space-y-2">
          <li>Choose whether to allow all bots to crawl your site.</li>
          <li>Optionally add a crawl delay to prevent server overload.</li>
          <li>Add paths you want to block from crawling (one per line).</li>
          <li>Enter your sitemap URL if you have one.</li>
          <li>Copy the generated content and save it as robots.txt in your website's root directory.</li>
        </ol>
      }
    >
      {toolSEO && <SEO title={toolSEO.seoTitle} description={toolSEO.seoDescription} />}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card>
          <CardContent className="p-6 space-y-4">
            <h3 className="font-semibold text-foreground mb-4">Configuration</h3>

            <div className="flex items-center space-x-2">
              <Checkbox
                id="allow-all"
                checked={allowAllBots}
                onCheckedChange={(checked) => setAllowAllBots(checked as boolean)}
                data-testid="checkbox-allow-all"
              />
              <Label htmlFor="allow-all" className="cursor-pointer">
                Allow all bots to crawl (recommended)
              </Label>
            </div>

            <div className="flex items-center space-x-2">
              <Checkbox
                id="crawl-delay"
                checked={enableCrawlDelay}
                onCheckedChange={(checked) => setEnableCrawlDelay(checked as boolean)}
                data-testid="checkbox-crawl-delay"
              />
              <Label htmlFor="crawl-delay" className="cursor-pointer">
                Enable crawl delay
              </Label>
            </div>

            {enableCrawlDelay && (
              <div className="ml-6">
                <Label htmlFor="delay-value">Delay (seconds)</Label>
                <Input
                  id="delay-value"
                  type="number"
                  min="1"
                  max="60"
                  value={crawlDelay}
                  onChange={(e) => setCrawlDelay(e.target.value)}
                  className="mt-1 w-32"
                  data-testid="input-crawl-delay"
                />
              </div>
            )}

            <div>
              <Label htmlFor="disallow-paths">Disallow Paths (one per line)</Label>
              <Textarea
                id="disallow-paths"
                placeholder={"/admin\n/private\n/temp"}
                value={disallowPaths}
                onChange={(e) => setDisallowPaths(e.target.value)}
                className="mt-1 min-h-[100px] font-mono text-sm"
                data-testid="textarea-disallow-paths"
              />
              <p className="text-xs text-muted-foreground mt-1">
                Enter paths you want to block from search engines
              </p>
            </div>

            <div>
              <Label htmlFor="sitemap-url">Sitemap URL</Label>
              <Input
                id="sitemap-url"
                type="url"
                placeholder="https://example.com/sitemap.xml"
                value={sitemapUrl}
                onChange={(e) => setSitemapUrl(e.target.value)}
                className="mt-1"
                data-testid="input-sitemap-url"
              />
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between mb-4 flex-wrap gap-2">
              <h3 className="font-semibold text-foreground">Generated robots.txt</h3>
              <div className="flex gap-2">
                <Button
                  onClick={copyToClipboard}
                  variant="outline"
                  size="sm"
                  data-testid="button-copy"
                >
                  {copied ? (
                    <Check className="w-4 h-4 mr-2" />
                  ) : (
                    <Copy className="w-4 h-4 mr-2" />
                  )}
                  {copied ? "Copied!" : "Copy"}
                </Button>
                <Button
                  onClick={downloadFile}
                  variant="outline"
                  size="sm"
                  data-testid="button-download"
                >
                  Download
                </Button>
              </div>
            </div>

            <Textarea
              value={output}
              readOnly
              className="min-h-[250px] font-mono text-sm bg-muted/50"
              data-testid="textarea-output"
            />

            <p className="text-xs text-muted-foreground mt-2">
              Save this file as "robots.txt" in your website's root directory (e.g., https://example.com/robots.txt)
            </p>
          </CardContent>
        </Card>
      </div>
    </ToolPageLayout>
  );
}
